"""Add identities and rest tokens

Revision ID: 10c3de3c85bf
Revises: 
Create Date: 2026-03-04 01:34:43.011556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '10c3de3c85bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('theme_color', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identities_id'), 'identities', ['id'], unique=False)
    op.add_column('habit_logs', sa.Column('used_rest_token', sa.Boolean(), nullable=True))
    op.drop_constraint('habit_logs_ibfk_1', 'habit_logs', type_='foreignkey')
    op.drop_constraint('habit_logs_ibfk_2', 'habit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'habit_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'habit_logs', 'habits', ['habit_id'], ['id'], ondelete='CASCADE')
    op.add_column('habit_summary', sa.Column('consistency_score', sa.Float(), nullable=True))
    op.drop_constraint('habit_summary_ibfk_2', 'habit_summary', type_='foreignkey')
    op.drop_constraint('habit_summary_ibfk_1', 'habit_summary', type_='foreignkey')
    op.create_foreign_key(None, 'habit_summary', 'habits', ['habit_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'habit_summary', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('habit_summary', 'current_streak')
    op.drop_column('habit_summary', 'longest_streak')
    op.add_column('habits', sa.Column('identity_id', sa.Integer(), nullable=True))
    op.add_column('habits', sa.Column('consistency_score', sa.Float(), nullable=True))
    op.drop_constraint('habits_ibfk_1', 'habits', type_='foreignkey')
    op.create_foreign_key(None, 'habits', 'identities', ['identity_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'habits', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('habits', 'streak')
    op.add_column('users', sa.Column('rest_tokens_available', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rest_tokens_available')
    op.add_column('habits', sa.Column('streak', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'habits', type_='foreignkey')
    op.drop_constraint(None, 'habits', type_='foreignkey')
    op.create_foreign_key('habits_ibfk_1', 'habits', 'users', ['user_id'], ['id'])
    op.drop_column('habits', 'consistency_score')
    op.drop_column('habits', 'identity_id')
    op.add_column('habit_summary', sa.Column('longest_streak', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('habit_summary', sa.Column('current_streak', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'habit_summary', type_='foreignkey')
    op.drop_constraint(None, 'habit_summary', type_='foreignkey')
    op.create_foreign_key('habit_summary_ibfk_1', 'habit_summary', 'users', ['user_id'], ['id'])
    op.create_foreign_key('habit_summary_ibfk_2', 'habit_summary', 'habits', ['habit_id'], ['id'])
    op.drop_column('habit_summary', 'consistency_score')
    op.drop_constraint(None, 'habit_logs', type_='foreignkey')
    op.drop_constraint(None, 'habit_logs', type_='foreignkey')
    op.create_foreign_key('habit_logs_ibfk_2', 'habit_logs', 'habits', ['habit_id'], ['id'])
    op.create_foreign_key('habit_logs_ibfk_1', 'habit_logs', 'users', ['user_id'], ['id'])
    op.drop_column('habit_logs', 'used_rest_token')
    op.drop_index(op.f('ix_identities_id'), table_name='identities')
    op.drop_table('identities')
    # ### end Alembic commands ###
